// Code generated by MockGen. DO NOT EDIT.
// Source: sessions.go
//
// Generated by this command:
//
//	mockgen -source=sessions.go -destination=repo_mocks/mock_sessions.go -package=repo_mocks
//

// Package repo_mocks is a generated GoMock package.
package repo_mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/bete7512/scaffold/apps/api/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
	isgomock struct{}
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockSessionRepo) CreateSession(ctx context.Context, session *models.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockSessionRepoMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockSessionRepo)(nil).CreateSession), ctx, session)
}

// FindSessionByToken mocks base method.
func (m *MockSessionRepo) FindSessionByToken(ctx context.Context, tokenHash []byte) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSessionByToken", ctx, tokenHash)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionByToken indicates an expected call of FindSessionByToken.
func (mr *MockSessionRepoMockRecorder) FindSessionByToken(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionByToken", reflect.TypeOf((*MockSessionRepo)(nil).FindSessionByToken), ctx, tokenHash)
}

// RevokeSession mocks base method.
func (m *MockSessionRepo) RevokeSession(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockSessionRepoMockRecorder) RevokeSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockSessionRepo)(nil).RevokeSession), ctx, id)
}

// RevokeUserSessions mocks base method.
func (m *MockSessionRepo) RevokeUserSessions(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeUserSessions indicates an expected call of RevokeUserSessions.
func (mr *MockSessionRepoMockRecorder) RevokeUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeUserSessions", reflect.TypeOf((*MockSessionRepo)(nil).RevokeUserSessions), ctx, userID)
}

// RotateRefreshToken mocks base method.
func (m *MockSessionRepo) RotateRefreshToken(ctx context.Context, session *models.Session, currentHash []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefreshToken", ctx, session, currentHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateRefreshToken indicates an expected call of RotateRefreshToken.
func (mr *MockSessionRepoMockRecorder) RotateRefreshToken(ctx, session, currentHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefreshToken", reflect.TypeOf((*MockSessionRepo)(nil).RotateRefreshToken), ctx, session, currentHash)
}
