// Code generated by MockGen. DO NOT EDIT.
// Source: processed_events.go
//
// Generated by this command:
//
//	mockgen -source=processed_events.go -destination=repo_mocks/mock_processed_events.go -package=repo_mocks
//

// Package repo_mocks is a generated GoMock package.
package repo_mocks

import (
	context "context"
	reflect "reflect"

	repos "github.com/bete7512/scaffold/apps/api/repos"
	db "github.com/bete7512/scaffold/pkg/db"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessedEventRepo is a mock of ProcessedEventRepo interface.
type MockProcessedEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockProcessedEventRepoMockRecorder
	isgomock struct{}
}

// MockProcessedEventRepoMockRecorder is the mock recorder for MockProcessedEventRepo.
type MockProcessedEventRepoMockRecorder struct {
	mock *MockProcessedEventRepo
}

// NewMockProcessedEventRepo creates a new mock instance.
func NewMockProcessedEventRepo(ctrl *gomock.Controller) *MockProcessedEventRepo {
	mock := &MockProcessedEventRepo{ctrl: ctrl}
	mock.recorder = &MockProcessedEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessedEventRepo) EXPECT() *MockProcessedEventRepoMockRecorder {
	return m.recorder
}

// MarkEventProcessed mocks base method.
func (m *MockProcessedEventRepo) MarkEventProcessed(ctx context.Context, eventID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkEventProcessed", ctx, eventID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkEventProcessed indicates an expected call of MarkEventProcessed.
func (mr *MockProcessedEventRepoMockRecorder) MarkEventProcessed(ctx, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkEventProcessed", reflect.TypeOf((*MockProcessedEventRepo)(nil).MarkEventProcessed), ctx, eventID)
}

// WithTx mocks base method.
func (m *MockProcessedEventRepo) WithTx(tx db.DBTX) repos.ProcessedEventRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repos.ProcessedEventRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockProcessedEventRepoMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockProcessedEventRepo)(nil).WithTx), tx)
}
