// Code generated by MockGen. DO NOT EDIT.
// Source: outbox.go
//
// Generated by this command:
//
//	mockgen -source=outbox.go -destination=repo_mocks/mock_outbox.go -package=repo_mocks
//

// Package repo_mocks is a generated GoMock package.
package repo_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/bete7512/scaffold/apps/api/models"
	repos "github.com/bete7512/scaffold/apps/api/repos"
	db "github.com/bete7512/scaffold/pkg/db"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxRepo is a mock of OutboxRepo interface.
type MockOutboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepoMockRecorder
	isgomock struct{}
}

// MockOutboxRepoMockRecorder is the mock recorder for MockOutboxRepo.
type MockOutboxRepoMockRecorder struct {
	mock *MockOutboxRepo
}

// NewMockOutboxRepo creates a new mock instance.
func NewMockOutboxRepo(ctrl *gomock.Controller) *MockOutboxRepo {
	mock := &MockOutboxRepo{ctrl: ctrl}
	mock.recorder = &MockOutboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepo) EXPECT() *MockOutboxRepoMockRecorder {
	return m.recorder
}

// ClaimOutboxEvents mocks base method.
func (m *MockOutboxRepo) ClaimOutboxEvents(ctx context.Context, limit int) ([]models.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOutboxEvents", ctx, limit)
	ret0, _ := ret[0].([]models.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOutboxEvents indicates an expected call of ClaimOutboxEvents.
func (mr *MockOutboxRepoMockRecorder) ClaimOutboxEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOutboxEvents", reflect.TypeOf((*MockOutboxRepo)(nil).ClaimOutboxEvents), ctx, limit)
}

// CreateOutboxEvent mocks base method.
func (m *MockOutboxRepo) CreateOutboxEvent(ctx context.Context, e *models.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOutboxEvent", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOutboxEvent indicates an expected call of CreateOutboxEvent.
func (mr *MockOutboxRepoMockRecorder) CreateOutboxEvent(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOutboxEvent", reflect.TypeOf((*MockOutboxRepo)(nil).CreateOutboxEvent), ctx, e)
}

// DeleteOutboxEventsPublishedBefore mocks base method.
func (m *MockOutboxRepo) DeleteOutboxEventsPublishedBefore(ctx context.Context, before time.Time, limit int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOutboxEventsPublishedBefore", ctx, before, limit)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOutboxEventsPublishedBefore indicates an expected call of DeleteOutboxEventsPublishedBefore.
func (mr *MockOutboxRepoMockRecorder) DeleteOutboxEventsPublishedBefore(ctx, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOutboxEventsPublishedBefore", reflect.TypeOf((*MockOutboxRepo)(nil).DeleteOutboxEventsPublishedBefore), ctx, before, limit)
}

// MarkOutboxEventsPublished mocks base method.
func (m *MockOutboxRepo) MarkOutboxEventsPublished(ctx context.Context, ids []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkOutboxEventsPublished", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkOutboxEventsPublished indicates an expected call of MarkOutboxEventsPublished.
func (mr *MockOutboxRepoMockRecorder) MarkOutboxEventsPublished(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkOutboxEventsPublished", reflect.TypeOf((*MockOutboxRepo)(nil).MarkOutboxEventsPublished), ctx, ids)
}

// WithTx mocks base method.
func (m *MockOutboxRepo) WithTx(tx db.DBTX) repos.OutboxRepo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repos.OutboxRepo)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockOutboxRepoMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockOutboxRepo)(nil).WithTx), tx)
}
