// Command openapi-bundle resolves the multi-file OpenAPI source under api/openapi into
// one self-contained document.
//
// Why it exists: the spec is authored as a root file plus paths/*.yaml and
// components/*.yaml, but oapi-codegen v2.8 cannot generate a single
// package from path items that are external $refs — its `import-mapping: "-"`
// (same-package) mode emits `.Type` with an empty package qualifier and skips models
// whose root entry is an external ref. Every downstream consumer wants one file anyway:
// oapi-codegen, the embedded spec behind GetSwagger(), the request-validation
// middleware, /openapi.json, Scalar, and the frontend's openapi-typescript client.
//
// The output is deterministic (kin-openapi marshals to maps; yaml.v3 sorts keys), so
// `make gen-check` catches a stale bundle the same way it catches stale Go code.
//
// Usage: go run ./scripts/openapi-bundle [-in api/openapi/openapi.yaml] [-out gen/openapi/openapi.bundle.yaml]
package main

import (
	"bytes"
	"context"
	"flag"
	"fmt"
	"os"
	"path"

	"github.com/getkin/kin-openapi/openapi3"
	"go.yaml.in/yaml/v3"
)

const header = `# Code generated by scripts/openapi-bundle from api/openapi/; DO NOT EDIT.
# Edit the source files under api/openapi/ and run ` + "`make gen-openapi`" + `.
`

func main() {
	in := flag.String("in", "apps/api/openapi/openapi.yaml", "root OpenAPI document (multi-file $refs allowed)")
	out := flag.String("out", "apps/api/gen/openapi/openapi.bundle.yaml", "bundled, self-contained output")
	flag.Parse()

	if err := run(*in, *out); err != nil {
		fmt.Fprintln(os.Stderr, "openapi-bundle:", err)
		os.Exit(1)
	}
}

func run(in, out string) error {
	ctx := context.Background()

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	doc, err := loader.LoadFromFile(in)
	if err != nil {
		return fmt.Errorf("load %s: %w", in, err)
	}
	// Validate the source before bundling: a bundle of a broken spec would only move the
	// error to oapi-codegen's less specific message.
	if err := doc.Validate(ctx); err != nil {
		return fmt.Errorf("validate %s: %w", in, err)
	}

	// Pull every external component into #/components/<kind>/<Name>, named by the last
	// segment of the referenced pointer, so a schema keeps its authored name whether it
	// lives in components/*.yaml or in a paths/<resource>.yaml components block.
	doc.InternalizeRefs(ctx, func(_ *openapi3.T, ref openapi3.ComponentRef) string {
		return path.Base(ref.RefPath().Fragment)
	})
	if err := doc.Validate(ctx); err != nil {
		return fmt.Errorf("validate bundled document: %w", err)
	}

	node, err := doc.MarshalYAML()
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	var buf bytes.Buffer
	buf.WriteString(header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(node); err != nil {
		return fmt.Errorf("encode yaml: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("encode yaml: %w", err)
	}

	if err := os.MkdirAll(path.Dir(out), 0o750); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	if err := os.WriteFile(out, buf.Bytes(), 0o644); err != nil { //nolint:gosec // spec file, not a secret
		return fmt.Errorf("write %s: %w", out, err)
	}
	return nil
}
